### PR TITLE
Create models #11

### PR DESCRIPTION
**Pull request by TGOlson**
Correctly posts a model to the server for a provided datasource. The `worker` service isn't able to process the request because the server doesn't quite understand columns yet (well, and the columns posted from the client are fake...).

Thought: endpoint should be structured `datasources/:id/models` if models are going to be directly tied to a datasource. This would make posting and getting models for a specific datasource more standard. Could also expose `/models` to get a list of all models for all datasources.

### CODE REVIEW

**Comment by jackfirth** [comment]
+1 to `POST /datasources/:id/models` idea

**Comment by jackfirth** [comment]
`GET` for models should probably go through a top level `/models` and `/models/:id` route though, unless we really need to get only models for a particular datasource

**Comment by TGOlson** [comment]
Ya, /models makes sense, wasn't really sure what would be most useful for a user - view all models, or view all models for a particular datasource.

**Comment by jackfirth** [comment]
Now that #114 is merged in, the `GET /datasources/:id` route now lists what column names are in the datasource. Should this be updated to use that, or should it be merged in and then a separate PR set up to use those?

**Pull request merged**
